version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27023:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

  fastapi:
    build: ./backend
    container_name: fastapi_trazabilidad
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://root:root@mongo:27017/

volumes:
  mongo_data:
